// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7y_tl-KICgT4xyNuxZqY6IU_Lbpawpmg',
    appId: '1:831164620978:web:00e92555d4e2f5b3c769ab',
    messagingSenderId: '831164620978',
    projectId: 'edproject-8b9c8',
    authDomain: 'edproject-8b9c8.firebaseapp.com',
    storageBucket: 'edproject-8b9c8.firebasestorage.app',
    measurementId: 'G-S75PN8P9TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi3cuhF8hsIRWK8YYn6G1OEcRaoiREAJg',
    appId: '1:831164620978:android:628cf8692d512d48c769ab',
    messagingSenderId: '831164620978',
    projectId: 'edproject-8b9c8',
    storageBucket: 'edproject-8b9c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB2H-VR5K83TH08TJWkLwSFlcv8MzgI9M',
    appId: '1:831164620978:ios:1693f6f0468f78fdc769ab',
    messagingSenderId: '831164620978',
    projectId: 'edproject-8b9c8',
    storageBucket: 'edproject-8b9c8.firebasestorage.app',
    iosBundleId: 'com.example.dddd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB2H-VR5K83TH08TJWkLwSFlcv8MzgI9M',
    appId: '1:831164620978:ios:1693f6f0468f78fdc769ab',
    messagingSenderId: '831164620978',
    projectId: 'edproject-8b9c8',
    storageBucket: 'edproject-8b9c8.firebasestorage.app',
    iosBundleId: 'com.example.dddd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7y_tl-KICgT4xyNuxZqY6IU_Lbpawpmg',
    appId: '1:831164620978:web:7c79cadcecaf88e6c769ab',
    messagingSenderId: '831164620978',
    projectId: 'edproject-8b9c8',
    authDomain: 'edproject-8b9c8.firebaseapp.com',
    storageBucket: 'edproject-8b9c8.firebasestorage.app',
    measurementId: 'G-KSE8M5HX12',
  );
}
